# -*- coding: utf-8 -*-
"""IA- ava2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lmj36aP9x__v4ojZeIg0367Z_EpEEMny
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.linear_model import LinearRegression
#carregando o dataset
dataset = pd.read_csv('/content/averrage sceen time by country.csv')
print(dataset)
#pré-processamento - #verificando se existem NaN
#print(dataset.isna().sum())
#irei tirar a coluna de bandeiras, pois não é  relevante
dataset_new = (dataset.drop(["Flag"], axis=1))
#print(dataset_new)

#criando um dicionário para os paises, pois não aceita string
dataset_dic = {'Country':['Argentina','Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'Czechia', 'Denmark', 'Egypt', 'France', 'Germany', 'Greece', 'Hong Kong', 'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Malaysia', 'Mexico', 'Netherlands', 'New Zealand', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia', 'Singapore', 'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'U.A.E', 'UK', 'USA', 'Vietnam', 'Worldwide']}# dicionario
dataset_new = pd.DataFrame(dataset_dic)
lb = LabelEncoder()
dataset_new['Country1'] = lb.fit_transform(dataset["Country"])
print(dataset_new)
print(dataset_new.info())
print(dataset_new.isna().sum())

#transformando o tempo em números inteiro, pois não aceita no formato de tempo
def converter_tempo_inteiro(tempo):
  formato_tempo = "%M:%S"  # Define o formato do tempo
  tempo_objeto = datetime.strptime(tempo, formato_tempo)

  horas = tempo_objeto.hour
  minutos = tempo_objeto.minute
  segundos = tempo_objeto.second

  valor_int =  (minutos * 60 + segundos)/60

  return valor_int

time = {'Total Time Spent on Devices': ['09:01', '05:51', '05:22','05:27', '09:32', '06:35', '08:36', '05:25', '09:01', '06:13', '04:58', '07:41', '05:26', '05:12', '06:00', '06:26', '06:23', '07:42', '05:59', '07:08', '05:55', '03:45', '08:06', '08:07', '05:27', '06:12', '09:14', '06:42', '07:37', '07:03', '07:57', '07:20', '06:59', '09:38', '05:21', '05:45', '06:02', '05:38', '07:14', '08:06', '07:24', '07:29', '05:47', '06:59', '06:23', '06:37']}
dataset_new = pd.DataFrame(time)
dataset_new['Tempo'] = dataset_new['Total Time Spent on Devices'].apply(converter_tempo_inteiro)
print(dataset_new)

#transformando outra coluna
def converter_tempo_inteiro(tempo_movel):
  formato_tempo = "%M:%S"  # Define o formato do tempo
  tempo_objeto = datetime.strptime(tempo_movel, formato_tempo)

  horas = tempo_objeto.hour
  minutos = tempo_objeto.minute
  segundos = tempo_objeto.second

  valor_int =  (minutos * 60 + segundos)/60

  return valor_int

time = {'Internet via Mobiles': ['04:55', '02:59', '02:59','02:19', '05:28', '03:04', '04:46', '03:16', '04:50', '02:53', '02:14', '04:20', '02:34', '02:29', '02:56', '03:17', '03:55', '04:53', '03:07', '03:36', '02:56', '01:54', '04:28', '04:32', '02:46', '03:07', '05:31', '03:17', '03:41', '04:08', '03:40', '04:13', '03:16', '05:13', '02:35', '02:53', '03:01', '02:32', '04:01', '05:05', '04:26', '04:18', '02:52', '03:28', '03:32', '03:46']}
dataset_new = pd.DataFrame(time)
dataset_new['Tempo_movel'] = dataset_new['Internet via Mobiles'].apply(converter_tempo_inteiro)
print(dataset_new)

#transformando outras duas colunas
dataset = pd.DataFrame({"Mobile Internet Speed (Mbps)" :[22.17, 86.01, 61.19, 56.18, 33.36, 82.68, 25.85,  109.4, 	10.82, 44.46, 113.44, 22.17, 59.66, 56.18,61.4,56.51, 18.26, 17.27,	24.84, 27.18, 39.25, 40.92, 36.34, 24.07, 109.06, 56.64, 24.04, 40.92, 62.95, 41.09, 21.73, 90.49, 72.18, 36.7, 118.76, 36.07, 85.64, 77.36, 68.04, 37.85, 31.93, 139.41, 46.02, 74.83, 39.59, 33.97  ]})
dataset["Mobile Internet Speed (Mbps)"] = dataset["Mobile Internet Speed (Mbps)"].round().astype(int)
print(dataset)
dataset = pd.DataFrame({"Fixed Internet Speed (Mbps)" :[60.25, 53.06, 67.23, 86.7, 97.52, 136.87, 216.46, 214.58, 89.61, 52.78, 188.35, 45.79, 150.15, 80.69, 42.79, 194.35, 49.09, 24.32, 77.91, 95.66, 60.12, 150.32, 91.5, 49.91, 120.82, 133.18, 81.42, 95.95, 119.06, 170.25, 74.92, 88.12, 214.23, 40.12, 95.34, 166.78, 107.83, 144.78, 124.14, 205.63, 31.86, 186.76, 73.21, 189.48, 80.27, 74.54 ]})
dataset["Fixed Internet Speed (Mbps)"] = dataset["Fixed Internet Speed (Mbps)"].round().astype(int)
print(dataset)


#criando um dataset com as colunas transformadas
coluna1 = pd.DataFrame({"Country1": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 ,32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]})
coluna2 = pd.DataFrame({"tempo": [9.016667, 5.850000, 5.366667, 5.450000, 9.533333, 6.583333, 8.600000, 5.416667, 9.016667, 6.216667, 4.966667, 7.683333,5.433333,5.200000,6.000000,6.433333,6.383333,7.700000,5.983333,7.133333, 5.916667, 3.750000,8.100000,8.116667,5.450000,6.200000,9.233333,6.700000,7.616667,7.050000,7.950000,7.333333,6.983333,9.633333,5.350000,5.750000,6.033333,5.633333,7.233333,8.100000,7.400000,7.483333,5.783333,6.983333,6.383333, 6.616667]})
coluna3 = pd.DataFrame({"tempo_movel": [ 4.916667, 2.983333,2.983333,2.316667,5.466667,3.066667,4.766667,3.266667,4.833333,2.883333,2.233333,4.333333,2.566667,2.483333,2.933333,3.283333,3.916667,4.883333,3.116667,3.600000,2.933333,1.900000,4.466667,4.533333,2.766667,3.116667,5.516667,3.283333,3.683333,4.133333,3.666667,4.216667,3.266667,5.216667,2.583333,2.883333,3.016667,2.533333,4.016667,5.083333,4.433333,4.300000,2.866667,3.466667,3.533333,3.766667]})
coluna4 = pd.DataFrame({"Mobile Internet Speed (Mbps)": [ 22,86,61,56,33,83,26,109, 11,44,113,22, 60,56,61,57,18,17,25,27,39, 41,36, 24,109,57,24,41,63,41,22,90,72,37,119,36,86,77,68,38,32,139,46,75,40,34]})
coluna5 = pd.DataFrame({"Fixed Internet Speed (Mbps)": [60,53,67,87,98,137,216,215,90,53,188,46,150,81,43,194,49,24,78,96,60,150,92,50,121,133,81,96,119,170,75,88,214,40,95,167,108,145,124,206,32,187,73,189,80,75]})
df = pd.concat([coluna1, coluna2, coluna3, coluna4, coluna5], axis=1)
print(df)


#questão 1:Verifique qual atributo será o alvo para regressão no seu dataset e
# faça uma análise de qual atributo é mais relevante para realizar a regressão do alvo escolhido.
# Lembre de comprovar via gráfico. Obs: Registrar na seção de resultados a análise realizada e discutir sobre o resultado encontrado.
X = df.drop("tempo", axis=1).values
y = df["tempo"].values
names = df.drop("tempo", axis=1).columns
lasso = Lasso(alpha=0.1)
lasso_coef = lasso.fit(X, y).coef_
plt.bar(names, lasso_coef)
plt.xticks(rotation = 45)
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
X = df.drop("tempo_movel", axis=1).values
y = df["tempo_movel"].values
print(type(X), type(y))
X_bmi = X[:, 3]
print(y.shape, X_bmi.shape)
X_bmi = X_bmi.reshape(-1, 1)
print(X_bmi.shape)

reg = LinearRegression()
reg.fit(X_bmi, y)
predictions = reg.predict(X_bmi)
plt.scatter(X_bmi, y)
plt.plot(X_bmi, predictions)
plt.ylabel("")
plt.xlabel("tempo_movel")
plt.show()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state = 42)

reg_all = LinearRegression()
reg_all.fit(X_train, y_train)
y_pred = reg_all.predict(X_test)

#R_squared
reg_all.score(X_test, y_test)


#RMSE
#mean_squared_error(y_test, y_pred, squared = False)
#RMSE
mean_squared_error(y_test, y_pred, squared = False)
rss = np.sum((y_pred - y_test) ** 2)
print(rss)
mse = mean_squared_error(y_test, y_pred)
print(mse)

#RMSE
mean_squared_error(y_test, y_pred, squared = False)

rss = np.sum((y_pred - y_test) ** 2)
print(rss)
mse = mean_squared_error(y_test, y_pred)
print(mse)

from sklearn.linear_model import Lasso, Ridge
from sklearn.model_selection import GridSearchCV



X = df[['tempo_movel']]
y = df['tempo']

parametros_lasso = {'alpha': [0.001, 0.01, 0.1, 1, 10]}
parametros_ridge = {'alpha': [0.001, 0.01, 0.1, 1, 10]}

regressor_lasso = Lasso()
regressor_ridge = Ridge()


grid_search_lasso = GridSearchCV(regressor_lasso, parametros_lasso, cv=5)
grid_search_lasso.fit(X, y)

melhor_param_lasso = grid_search_lasso.best_params_
melhor_score_lasso = grid_search_lasso.best_score_

print("Melhor parametrização para Lasso:", melhor_param_lasso)
print("Melhor score para Lasso:", melhor_score_lasso)


grid_search_ridge = GridSearchCV(regressor_ridge, parametros_ridge, cv=5)
grid_search_ridge.fit(X, y)

melhor_param_ridge = grid_search_ridge.best_params_
melhor_score_ridge = grid_search_ridge.best_score_

print("Melhor parametrização para Ridge:", melhor_param_ridge)
print("Melhor score para Ridge:", melhor_score_ridge)

from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso, Ridge

kf = KFold(n_splits = 5, shuffle = True, random_state = 42)
param_grid = {"alpha":np.arange(0.001, 1, 10), "solver": ["sag", "lsqr"]}

ridge = Ridge()
ridge_cv = GridSearchCV(ridge, param_grid, cv = kf)
ridge_cv.fit(X_train, y_train)
print(ridge_cv.best_params_, ridge_cv.best_score_ )

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({ 
    "Country1": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 ,32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    "tempo": [9.016667, 5.850000, 5.366667, 5.450000, 9.533333, 6.583333, 8.600000, 5.416667, 9.016667, 6.216667, 4.966667, 7.683333,5.433333,5.200000,6.000000,6.433333,6.383333,7.700000,5.983333,7.133333, 5.916667, 3.750000,8.100000,8.116667,5.450000,6.200000,9.233333,6.700000,7.616667,7.050000,7.950000,7.333333,6.983333,9.633333,5.350000,5.750000,6.033333,5.633333,7.233333,8.100000,7.400000,7.483333,5.783333,6.983333,6.383333, 6.616667], 
    "tempo_movel": [ 4.916667, 2.983333,2.983333,2.316667,5.466667,3.066667,4.766667,3.266667,4.833333,2.883333,2.233333,4.333333,2.566667,2.483333,2.933333,3.283333,3.916667,4.883333,3.116667,3.600000,2.933333,1.900000,4.466667,4.533333,2.766667,3.116667,5.516667,3.283333,3.683333,4.133333,3.666667,4.216667,3.266667,5.216667,2.583333,2.883333,3.016667,2.533333,4.016667,5.083333,4.433333,4.300000,2.866667,3.466667,3.533333,3.766667], 
    "Mobile Internet Speed (Mbps)":[ 22,86,61,56,33,83,26,109, 11,44,113,22, 60,56,61,57,18,17,25,27,39, 41,36, 24,109,57,24,41,63,41,22,90,72,37,119,36,86,77,68,38,32,139,46,75,40,34],
    "Fixed Internet Speed (Mbps)":[60,53,67,87,98,137,216,215,90,53,188,46,150,81,43,194,49,24,78,96,60,150,92,50,121,133,81,96,119,170,75,88,214,40,95,167,108,145,124,206,32,187,73,189,80,75]
}) 

df.plot(x="Country1", y=["tempo" ], kind="bar")

df.plot(x="Country1", y=["tempo_movel"], kind="bar")

df.plot(x="Country1", y=["Mobile Internet Speed (Mbps)"], kind="bar")

df.plot(x="Country1", y=["Fixed Internet Speed (Mbps)" ], kind="bar")